const PRODUCT_INFO = {
  name: 'UZUM',
  description: 'Generated by create next app',
  logo: '/logo_Uzum.png',
  favicon: '/logo_Uzum.png',
  url: 'https://www.shadcnblocks.com',
  socials: {
    telegram: 'https://t.me/usmanov_dev',
    instagram: 'https://t.me/usmanov_dev',
    youtube: 'https://t.me/usmanov_dev',
    linkedin: 'https://www.linkedin.com/in/usmonov-azizbek/',
  },
  contact: {
    phone: '+998901234567',
    email: 'contact@fias.uz',
  },
  terms_of_use: '',
  creator: 'FIAS App',
};

export { PRODUCT_INFO };
